import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/') })

test('listed file checks define the result without a compaction or restart gate', async ({ page }) => {
  const panel = page.getByTestId('orb-panel')
  for (const [name, label] of [['所列检查通过', '所列依据一致'], ['发现约束偏差', '发现检查偏差'], ['关键证据缺失', '证据待补齐']]) {
    await page.getByRole('group', { name: '演示状态' }).getByRole('button', { name }).click()
    await expect(panel.locator('.risk-value h2')).toHaveText(label)
    await expect(panel.getByTestId('semantic-card')).not.toContainText('%')
    await expect(panel).toContainText('新开收益尚未评估')
    await expect(panel).not.toContainText('建议新开')
  }
  await expect(panel.locator('.signal-preview')).toHaveCount(2)
  await expect(panel.locator('.signal-preview').first()).toContainText('待核验')
  await expect(panel.locator('.overview-gap')).toContainText('键盘导航检查需要实际交互')
  await expect(panel.locator('.clear-result')).toHaveCount(0)
})

test('actual checks, declarations and file hashes stay distinguishable', async ({ page }) => {
  await page.getByRole('button', { name: '查看检查与来源' }).click()
  await expect(page.locator('.evidence-item')).toHaveCount(2)
  await expect(page.locator('.evidence-item').first()).toContainText('未通过')
  await expect(page.locator('.probe-expected').first()).toHaveText("saveMode: 'manual'")
  await expect(page.locator('.source-item').first()).toContainText('评估者声明')
  await expect(page.locator('.source-item').last()).toContainText('SHA-256')
  await expect(page.getByTestId('orb-panel')).toContainText('尚非独立验证')
  await page.getByRole('button', { name: '模拟修改并重新采集' }).click()
  await expect(page.getByTestId('orb-panel').locator('.risk-value h2')).toHaveText('所列依据一致')
  await expect(page.locator('.check-tally')).toContainText('0 偏差')
})

test('superseded requirements remain visible without entering the active checklist', async ({ page }) => {
  await page.getByRole('button', { name: '旧方案已作废' }).click()
  await expect(page.locator('.ledger-superseded')).toContainText('切换为自动保存')
  await expect(page.locator('.ledger-active').filter({ hasText: '保存方式保持 manual' })).toContainText('替代：旧方案')
  await page.getByRole('button', { name: '返回概览' }).click()
  await expect(page.getByTestId('orb-panel').locator('.risk-value h2')).toHaveText('所列依据一致')
  await page.getByRole('button', { name: '查看检查与来源' }).click()
  await expect(page.locator('.evidence-item')).toHaveCount(2)
})

test('copying a collection prompt does not claim a check has run', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: '关键证据缺失' }).click()
  await page.getByRole('button', { name: '查看检查与来源' }).click()
  await page.getByRole('button', { name: '准备重新收集' }).click()
  await expect(page.getByRole('textbox', { name: '证据检查指令' })).toContainText('$context-health')
  await page.getByRole('button', { name: '复制检查指令' }).click()
  await expect(page.getByRole('status')).toContainText('检查尚未运行')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('$context-health')
})

test('elapsed time does not erase an as-of receipt and historical views cannot replace latest', async ({ page }) => {
  await page.clock.install()
  await page.reload()
  await page.clock.fastForward(21 * 60 * 1000)
  await expect(page.getByTestId('orb-panel').locator('.risk-value h2')).toHaveText('发现检查偏差')
  await page.getByRole('button', { name: '查看检查与来源' }).click()
  await expect(page.getByTestId('orb-panel')).toContainText('截至采集时点')
  await page.getByRole('button', { name: '查看采集历史' }).click()
  await expect(page.locator('.history-item')).toHaveCount(2)
  await page.locator('.history-item').last().click()
  await expect(page.getByTestId('orb-panel')).toContainText('历史收据')
  await expect(page.locator('.probe-pass')).toHaveCount(2)
  await page.getByRole('button', { name: '返回概览' }).click()
  await expect(page.getByTestId('orb-panel').locator('.risk-value h2')).toHaveText('发现检查偏差')
})

test('pinning and snooze stay isolated across background events and session switches', async ({ page }) => {
  await page.getByRole('button', { name: '模拟后台会话更新' }).click()
  await expect(page.getByTestId('bound-session')).toHaveText('设置页交互优化')
  await page.getByRole('button', { name: '稍后提醒', exact: true }).click()
  await expect(page.locator('.orb-button')).toHaveClass(/snoozed/)
  await page.getByRole('button', { name: '展开 Context Orb' }).click()
  await page.getByRole('button', { name: '选择固定会话' }).click()
  await page.getByRole('button', { name: /^设置页验证（后台）/ }).click()
  await expect(page.locator('.orb-button')).not.toHaveClass(/snoozed/)
  await page.getByRole('button', { name: '选择固定会话' }).click()
  await page.getByRole('button', { name: /^设置页交互优化/ }).click()
  await expect(page.locator('.orb-button')).toHaveClass(/snoozed/)
  await page.getByRole('button', { name: '提醒设置' }).click()
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(page.locator('.orb-button')).not.toHaveClass(/snoozed/)
  await page.getByRole('button', { name: '返回概览' }).click()
  await page.getByRole('button', { name: '选择固定会话' }).click()
  await page.getByRole('button', { name: '解除固定' }).click()
  await expect(page.getByTestId('bound-session')).toHaveText('尚未固定会话')
})

test('the task brief is editable and copies exactly the reviewed text', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: '整理下一步简报' }).click()
  const text = page.getByRole('textbox', { name: '下一步任务简报' })
  await expect(text).toContainText('下一步任务简报')
  await text.fill('目标：完成设置页\n已验证：键盘导航\n下一步：检查错误反馈')
  await page.getByRole('button', { name: '复制任务简报' }).click()
  await expect(page.getByRole('status')).toContainText('已复制')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(await text.inputValue())
})

test('drag and right click do not toggle; keyboard and help focus work', async ({ page }) => {
  const orb = page.locator('.orb-button')
  const box = (await orb.boundingBox())!
  await page.mouse.move(box.x + 40, box.y + 40)
  await page.mouse.down()
  await page.mouse.move(box.x - 30, box.y + 10, { steps: 8 })
  await page.mouse.up()
  await expect(page.getByTestId('orb-panel')).toBeVisible()
  await orb.click({ button: 'right' })
  await expect(page.getByTestId('orb-panel')).toBeVisible()
  await page.keyboard.press('Escape')
  await orb.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('orb-panel')).not.toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByTestId('orb-panel')).toBeVisible()
  await page.getByRole('button', { name: '查看设计说明' }).click()
  await expect(page.getByRole('button', { name: '关闭设计说明' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: '开始体验' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '查看设计说明' })).toBeFocused()
})

test('narrow layout and theme changes retain usable controls', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '切换主题', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: '切换主题', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: '整理下一步简报' }).click()
  await expect(page.getByRole('textbox', { name: '下一步任务简报' })).toBeVisible()
})

test('release always docks the orb and opening the panel preserves its position', async ({ page }) => {
  const orb = page.locator('.orb-button')
  const stage = (await page.getByRole('region', { name: '悬浮球交互预览' }).boundingBox())!
  await page.getByRole('button', { name: '提醒设置' }).click()
  await page.getByRole('radio', { name: '关闭', exact: true }).check()
  await page.getByRole('button', { name: '返回概览' }).click()
  let box = (await orb.boundingBox())!
  await page.mouse.move(box.x + 40, box.y + 40)
  await page.mouse.down()
  await page.mouse.move(stage.x + stage.width / 2, stage.y + stage.height * .85, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.orb-dock')).toHaveClass(/is-snapped/)
  await page.locator('.orb-dock').evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
  box = (await orb.boundingBox())!
  expect(Math.abs(box.y + box.height - (stage.y + stage.height - 6))).toBeLessThan(2)
  const docked = box
  await orb.click()
  await expect(page.getByTestId('orb-panel')).toHaveCount(0)
  await orb.click()
  box = (await orb.boundingBox())!
  expect(box.x).toBeCloseTo(docked.x, 0)
  expect(box.y).toBeCloseTo(docked.y, 0)
  await page.getByRole('button', { name: '提醒设置' }).click()
  await page.getByRole('radio', { name: '仅限 Codex 窗口' }).check()
  await page.getByRole('button', { name: '返回概览' }).click()
  const target = (await page.locator('.mock-window').boundingBox())!
  await page.mouse.move(box.x + 40, box.y + 40)
  await page.mouse.down()
  await page.mouse.move(target.x + target.width / 2, target.y + 20, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.orb-dock')).toHaveClass(/is-snapped/)
  await page.locator('.orb-dock').evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
  box = (await orb.boundingBox())!
  expect(Math.abs(box.y + box.height - target.y)).toBeLessThan(2)
  await expect(page.locator('#orb-state-description')).toContainText('已吸附窗口边缘')
  const panel = (await page.getByTestId('orb-panel').boundingBox())!
  expect(panel.x).toBeGreaterThanOrEqual(stage.x)
  expect(panel.y).toBeGreaterThanOrEqual(stage.y)
  expect(panel.x + panel.width).toBeLessThanOrEqual(stage.x + stage.width)
  expect(panel.y + panel.height).toBeLessThanOrEqual(stage.y + stage.height)
})

test('compact widget keeps every detail reachable without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 382, height: 690 })
  await page.goto('/?surface=orb')
  await page.getByRole('button', { name: '展开 Context Orb' }).click()
  await page.getByRole('button', { name: '查看检查与来源' }).click()
  await page.getByRole('button', { name: '查看采集历史' }).click()
  await expect(page.locator('.history-item')).toHaveCount(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '返回概览' }).click()
  await page.getByRole('button', { name: '整理下一步简报' }).click()
  await expect(page.getByRole('textbox', { name: '下一步任务简报' })).toBeVisible()
})

test('risk color, capacity ring and optional count remain distinct and settings persist', async ({ page }) => {
  await page.getByRole('button', { name: '所列检查通过' }).click()
  await expect(page.locator('.orb-dock')).toHaveClass(/risk-aligned/)
  await expect(page.getByRole('progressbar', { name: '上下文使用量' })).toHaveAttribute('aria-valuenow', '98')
  await expect(page.locator('.orb-ring-fill')).toHaveAttribute('stroke-dashoffset', '2')
  await expect(page.getByTestId('compaction-readout')).toHaveCount(0)
  await page.getByRole('button', { name: '提醒设置' }).click()
  await expect(page.getByRole('radio')).toHaveCount(3)
  await expect(page.getByRole('radio', { name: '仅限 Codex 窗口' })).toBeChecked()
  await expect(page.getByRole('button', { name: /绑定 CLI/ })).toHaveCount(0)
  await page.getByRole('radio', { name: '关闭', exact: true }).check()
  await expect(page.getByTestId('orb-panel')).toContainText('松手后，平滑停靠当前屏幕最近的边缘')
  await page.getByRole('switch', { name: '球体动态配色' }).click()
  await expect(page.locator('.orb-dock')).toHaveClass(/risk-neutral/)
  await page.getByRole('switch', { name: '显示压缩次数' }).click()
  await page.getByRole('button', { name: '返回概览' }).click()
  await expect(page.getByTestId('compaction-readout')).toContainText('8')
  await expect(page.locator('.risk-value h2')).toHaveText('所列依据一致')
  await page.reload()
  await expect(page.getByTestId('compaction-readout')).toBeVisible()
  await page.getByRole('button', { name: '提醒设置' }).click()
  await expect(page.getByRole('radio', { name: '关闭', exact: true })).toBeChecked()
  await expect(page.getByRole('switch', { name: '球体动态配色' })).not.toBeChecked()
})
